spring:
#druid数据源的配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #指定数据源的类型   druid
    druid: 
      url: jdbc:mysql://127.0.0.1:3306/erp
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 3 
      minIdle: 3 
      maxActive: 30 
      maxWait: 15000 
      timeBetweenEvictionRunsMillis: 120000 
      minEvictableIdleTimeMillis: 300000 
      validationQuery: SELECT 'x' 
      testWhileIdle: true 
      testOnBorrow: false 
      testOnReturn: false 
      poolPreparedStatements: false 
      maxPoolPreparedStatementPerConnectionSize: 20 
      removeAbandoned: true 
      removeAbandonedTimeoutMillis: 20000 
      logAbandoned: true 
      logDifferentThread: true 
      #filters: log4j,stat 
      #connectionProperties:  druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000 
      useGlobalDataSourceStat: true 
  druid:
    web:
      druid-registration-url: /druid/* 
      login-username: root #监控后台登录名称 
      login-password: 123456 #监控后台登录密码
      allow: 
      deny: 
      filters-url-patterns: /*
      exclusions: '*.js,*.gif,*.jpg,*.jpeg,*.png,*.css,*.ico,*.jsp,/druid/*'

#mybatis的配置
mybatis:
  mapper-locations:   #配置mybatis的映射文件地址  注意一般放到resources里面
  - classpath:mapper/sys/*Mapper.xml    
  - classpath:mapper/bus/*Mapper.xml    
  #config-location: classpath:mybatis.cfg.xml
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   
#shrio的配置
shiro: 
  hash-algorithm-name: md5
  hash-iterations: 2
  web:
    ingore-urls:
    - '/login.html*'
    - '/login/toLogin*'
    - '/login/login*'
    - '/resources/**'
    log-outs:
    - '/login/logout'
    auth-urls:
    - '/**'
    login-url: 'login.html'
    success-url: 'index.html'
    unauthorized-url: '/error'   
    
#文件上传及文件下载的根路径
upload:
  uploadPath: 'D:/Test/upload'
    